### ISSUE TITLE
May I ask the IDE you use in the research?

### ISSUE THREAD

**Issue by NarcissusInMirror** [baidu-research/NCRF#11]

**Comment by yil8** [comment]
@NarcissusInMirror sublime + vim, lol

**Comment by yil8** [comment]
@NarcissusInMirror Can you close this issue if there is no further questions?

**Comment by NarcissusInMirror** [comment]
OK，I have closed it. 




发自网易邮箱大师


On 07/24/2018 02:30，Yi Li<notifications@github.com> wrote：

@NarcissusInMirror Can you close this issue if there is no further questions?

**Comment by NarcissusInMirror** [comment]
Thank you for your answer, I'm sorry that I forgot to check my e-mail last few days. It seems that my problem is quite unprofessional lol. Actually I 'm totally new to this field and know little, including I have to close the issue when the problem is get solve. Thank you anyway!




发自网易邮箱大师


在2018年07月24日 16:11，NarcissusInMirror<qiush_2015@163.com> 写道：
OK，I have closed it. 




发自网易邮箱大师


On 07/24/2018 02:30，Yi Li<notifications@github.com> wrote：

@NarcissusInMirror Can you close this issue if there is no further questions?

**Comment by yil8** [comment]
@NarcissusInMirror no don't worry! no problem is unprofessional, any questions are welcome here.
