### ISSUE TITLE
how to do 'hard negative mining'?

### ISSUE THREAD

**Issue by swy0915** [baidu-research/NCRF#17]
how to do 'hard negative mining'? can you share the process detail？thank you very much

**Comment by yil8** [comment]
@swy0915 This is the tricky part. Usually it includes two steps. The first random sampling step is easier, it starts with obtaining the tissue mask of each tumor slide. Then I randomly sample coordinates based on the tumor tissue mask and determine it's label based on the annotation. The code for the second hard negative mining part is messy, and it involves training a first model, obtain false tumor regions with high probability, and save them as coordinates.

**Comment by swy0915** [comment]
What do I need to do after i save  false tumor regions coordinates?

**Comment by swy0915** [comment]
@yil8 combined those coordinates with the randomly sampled ones,and retrain model again .and repeating this process?

**Comment by yil8** [comment]
@swy0915 I only do it once, but in theory repeatedly online hard negative mining is a better solution, which I'm actually thinking about working on it next. I combined the randomly sampled coordinates from the first step with the hard negative coordinates.

**Comment by swy0915** [comment]
@yil8 thank you very much, I will try ...
