### ISSUE TITLE
what if I patch the training images at level 1?

### ISSUE THREAD

**Issue by LXYTSOS** [baidu-research/NCRF#18]
If I patch the training images base on the level 1, 2, 3(still 768 by 768), should I downsample a image to the same level before sent it to testing?

**Comment by yil8** [comment]
@LXYTSOS If you train you images on different levels other than 0, I guess you have to do it on the same level for testing. I haven't tried on training on different levels other than 0 and would probably expect decrease on performance.

**Comment by LXYTSOS** [comment]
嗯好的，非常感谢，我试试。
