### ISSUE TITLE
about backend

### ISSUE THREAD

**Issue by lz666win** [baidu-research/NCRF#2]
I notice you use pytorch ,can you provide a tf or keras as beckend? I think it is good for study

**Comment by yil8** [comment]
@lz666win  I'll try my best to work out a tf version if I have enough time, but the performance may not match the pytorch version. Another difficulty is in tf, I don't know what's the equivalent for pytorch Dataset, which support easy multi process data loading. It seems even data loading has to be some ops within tf land, which is a bit headache for me.
