### ISSUE TITLE
A issue about the data 

### ISSUE THREAD

**Issue by sarsigmadelta** [baidu-research/NCRF#20]
.tif 图片的 level 6 图片，与level 0图片。图片的两条边的缩放比例不一样，导致wsi_producer.py 的 52行报错。
请问有人遇到这个问题吗，谢谢啦

![image](https://user-images.githubusercontent.com/28585937/44025444-c03f89c0-9f22-11e8-839c-f204f904a1c9.png)

**Comment by yil8** [comment]
@sarsigmadelta 这个issue 里提到过这个问题 #6
