### ISSUE TITLE
The ground truth of Test_026

### ISSUE THREAD

**Issue by Hukongtao** [baidu-research/NCRF#21]
How do you get the ground truth annotation of Test_026??

**Comment by yil8** [comment]
@Hukongtao The ground truth annotation of test set was originally provided from the organizers in *.tif format, but they later removed the *.tif format, only keeping the coordinates in *.xml format. As for how to generate the coordinates of pre-sampled patches, that's a long story and has been discussed here #14

**Comment by Hukongtao** [comment]
@yil8 In that case,Can you send me one tif format annotation?I will be very grateful to you. My QQ mail:1821141394@qq.com

**Comment by yil8** [comment]
@Hukongtao If you have received the ground truth tif of Test_026 and have no further questions on this issue. Can you please close it? Thanks
