### ISSUE TITLE
is the model in ckpt folder the trained model?

### ISSUE THREAD

**Issue by wenhuihuang1979** [baidu-research/NCRF#23]
is the model in ckpt the trained model? I used this model to run a testing for test_026, and get a different heatmap for baseline.
![image](https://user-images.githubusercontent.com/23426777/45334736-a90df000-b5ae-11e8-8fd0-4e3bb1919f3b.png)

**Comment by yil8** [comment]
@wenhuihuang1979 that is the trained model. When you plot the heatmap, can you try using the following setting?
``` python
In [1]: import numpy as np

In [2]: from matplotlib import pyplot as plt

In [3]: probs_map = np.load('test_026.npy')

In [4]: plt.imshow(probs_map.transpose(), vmin=0, vmax=1, cmap='jet')
Out[4]: <matplotlib.image.AxesImage at 0x7f35e994ca58>

In [5]: plt.show()
```
I would highly recommend using `cmap=jet` to plot the probability map as compared to your case, which does not quite differentiate numbers around 0.5. You can also refer to #12 for reproducing results.

**Comment by wenhuihuang1979** [comment]
@yil8 not the plot drawing problem here is I am testing for test_001, my heat map is
![image](https://user-images.githubusercontent.com/23426777/45396844-0322ba00-b670-11e8-914e-03e3ac20fc43.png)

However, your heatmap is
![image](https://user-images.githubusercontent.com/23426777/45396863-1cc40180-b670-11e8-828b-e38dd3a5be43.png)

**Comment by yil8** [comment]
@wenhuihuang1979 yeah, you definitely shouldn't use PyTorch 0.4, the API is significantly different than previous versions, e.g. they even get rid of Variable. Can you try PyTorch 0.3.1?
