### ISSUE TITLE
About how to generater Normal_*.json

### ISSUE THREAD

**Issue by ilikewind** [baidu-research/NCRF#26]
Hi, 

I was wondering how to generater Normal_*. json files? 

And if it was generatered by the normal tissue mask? can you share the process detail. Thank you!

Kind regards,

**Comment by yil8** [comment]
@ilikewind yes, for Normal_*.json files they were generated by random sampling coordinates from the normal tissue mask at some higher level, e.g. level 6.

**Comment by yil8** [comment]
@ilikewind It's always impossible to enumerate all the tissue regions of  a normal samples, so you have to do subsampling.

**Comment by yil8** [comment]
@ilikewind I'm not quite sure how you generated this figure, it seems the blue dots are concentrated about boundary regions. This might due to the effect of hard negative mining.

**Comment by ilikewind** [comment]
@yil8 the figure was generated by your file Normal-001.json at NCRF/jsons/train/.
And I am not sure if you mistake the json file for coordinates/normal_train.txt . It seems we are discuss different issues. 
Best wish.

**Comment by yil8** [comment]
@ilikewind I am so sorry, I was completely wrong about your question, and indeed I confused between Normal_001.json with coordinates/normal_train.txt. Normal_001.json was not really used through out this code base. Honestly, I forgot how Normal_*.json were generated, but they were probably not generated base on tissue mask

**Comment by ilikewind** [comment]
@yil8 Ok, thanks for your patient. I will do something about it.
