### ISSUE TITLE
The ground truth of Test_026 too

### ISSUE THREAD

**Issue by sangloupmonoutlook** [baidu-research/NCRF#28]
Can you send me one tif format annotation?I will be very grateful to you. My mail: sangloupmon@outlook.com

**Comment by yil8** [comment]
@sangloupmonoutlook Sorry but unfortunately, my data disk for the mask files were lost...I'm currently working with our system admin to see if I can get my data back.

**Comment by sangloupmonoutlook** [comment]
Thank you very much for your help.
