### ISSUE TITLE
Evaluation Mask Level in Evaluation_FROC

### ISSUE THREAD

**Issue by usamabaig1** [baidu-research/NCRF#30]
Can the Evaluation_Mask_Level in Evaluation_FROC can be different from the level at which the probability map was generated?
I mean you generated the prob maps at level 6 but evaluation is done at level 5. Any particular reason behind this?
p.s. I generated ground truth tif file mask at level 6. Does it matter?
Thankyou.
https://github.com/baidu-research/NCRF/blob/1c8987f73e2ccf717b605eb28913d47b4390c13d/wsi/bin/Evaluation_FROC.py#L214

**Comment by yil8** [comment]
@usamabaig1 The Evaluation_FROC level was set by the Camelyon16 competition organizers. Therefore, I guess it's better not change it so the results are comparable. It's an arbitrary choice for me to set level 6 for generating probability map. I haven't tried other levels, but I guess it won't matter that much.
