### ISSUE TITLE
confuse about hard example extracting

### ISSUE THREAD

**Issue by huangxiansong** [baidu-research/NCRF#38]
As in the readme 'Note that, coordinates of hard negative patches, typically around tissue boundary regions, are also includedwithin normal_train.txt and normal_valid.txt', and the code directly provide the coordinate list containing hard negative patches. 
But I could not find how these coordinates were generated. I don't sure if I miss something in the code about this question.

**Comment by yil8** [comment]
@huangxiansong no you are not. This is the tricky part.  Please refer to #14  for more details
