### ISSUE TITLE
The naming for coordinates used in normal_train.txt file is confusing.

### ISSUE THREAD

**Issue by fazish** [baidu-research/NCRF#39]
Hello 
The coords that you have shared with us was superb. It could not be more helpful. 
However, In the normal_train.txt file, the naming used for each whole slide images is a bit confusing. As it is for Normal part, we can see Tumor_094,80227,34836 in this file. I appreciate it if you can help me to understand whether it is a mistake and I should change the name with Normal_094,80227,34836 or there is another reason for that. 
Many thanks in advance for your help.

**Comment by yil8** [comment]
@fazish For tumor WSI, there is only a small fraction of the whole giant images that contain tumor cells, with the remaining still being normal cells.

**Comment by fazish** [comment]
dear @yil8, 
Many thanks for the response.
My question is why normal_training.txt file contains tumor_ naming in it.
Please look at the normal_training.txt file to see what I mean by that.

**Comment by yil8** [comment]
@fazish I guess I did not make myself clear. There are also lots of normal regions within tumor_xxx.tif, i.e. regions outside the tumor masks. So you can sample normal coordinates from these regions.
