### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by jeffshek** [baidu-research/NCRF#4]
If I build and write up the requirements and installation into a docker file (for easier adoption), would you be willing to accept that pull-request into this repo? If so, I'll gladly do that!

**Comment by yil8** [comment]
@jeffshek Thanks for your help! Honestly, I have zero experience in docker, but I'm definitely interested in give a try. Do you mind work out a little bit README as well?

**Comment by jeffshek** [comment]
Awesome! Docker has really helped onboarding installations and reduce the "works on my machine" problems. The numpy/scikit/pandas series can be quite a hurdle to install if the first attempt at putting it behind a virtualenv doesn't work, so this scares away too many people from contributing.

In the PR, I'll include both instructions (docker and non-docker) in the README.md.
