### ISSUE TITLE
如何挑选较好的模型

### ISSUE THREAD

**Issue by Ryanrenqian** [baidu-research/NCRF#43]
您好，我在使用您提供的代码跑出来的性能与论文差距较大，我想知道，您在训练时，是根据在valid上选择的吗？如果是 是根据哪些指标选择的了， 我发现有时候两个模型相比，acc差不多 但是在test上的分数却差异比较大？

**Comment by yil8** [comment]
@Ryanrenqian 你好，我是根据valid上选的哈，具体是根据loss_valid来选的，https://github.com/baidu-research/NCRF/blob/master/wsi/bin/train.py#L233
