### ISSUE TITLE
难样本挖掘问题

### ISSUE THREAD

**Issue by yangyang117** [baidu-research/NCRF#46]
您好，我看您在训练过程中使用了难样本挖掘技术，之前参看谷歌的论文，是将分类错误的图片进行多次训练，请问您的难样本挖掘是如何实现的呢？将tumor图像中的边缘地区截取出来作为负样本吗？

**Comment by yil8** [comment]
@yangyang117 你好，具体的话可以参照这个issue #14 ，确实如你所说，是将分类错误的图片再次拿出来进行二次训练，而且确实容易出现在边缘。
