### ISSUE TITLE
The ground truth of Test_026 too

### ISSUE THREAD

**Issue by Doloresru** [baidu-research/NCRF#47]
Can you send me one tif format annotation?I will be very grateful to you. My mail: 1780725543@qq.com

**Comment by yil8** [comment]
@Doloresru just sent, can you take a look?

**Comment by Doloresru** [comment]
> 
> 
> @Doloresru just sent, can you take a look?

Yes, I have receieved it. Thank you so much!

**Comment by liwenxi** [comment]
@Doloresru @yil8 Hello, can you share this test_026.tif now? My mail: wenxi.li@sjtu.edu.cn. Thank you!
