### ISSUE TITLE
关于test数据集中mask.tif

### ISSUE THREAD

**Issue by XiaoXueShengwangrui** [baidu-research/NCRF#48]
您好，能否提供一份测试集的tif格式的标注mask。我的邮箱316625707@qq.com
ps：我一直是利用.xml的标注使用cv2.fillPoly来生成的只有单个倍率tif的mask，但我觉得这样的标注mask似乎并不准确。

**Comment by yil8** [comment]
@XiaoXueShengwangrui 你好，可遗憾测试集的tif mask之前只有官方提供下载，后来他们删除了。

**Comment by XiaoXueShengwangrui** [comment]
好的，谢谢你
