### ISSUE TITLE
downsampling level selection

### ISSUE THREAD

**Issue by sketchplanet** [baidu-research/NCRF#5]
The heatmap generated by mask downsampled in level 8 and the heatmap generated by mask downsampled in level 6 difffers a lot. How to choose the downsampling level when generating the heatmap ? Why cause this?  A little confused , Thank you!

**Comment by yil8** [comment]
@sketchplanet Generally, speaking smaller level heat map means smaller inference stride, e.g. (level 8 = 256, vs level 6 = 64). Smaller inference stride typically get you higher sensitivity with the sacrifice of more computation. The wining team of camelyon16 used an inference stride of 4, which is computationally infeasible in my current implementation for obtaining the heat map.

**Comment by sketchplanet** [comment]
Previously I generate heatmap in level 8(extracting patch without overlap). I didn't realize the huge difference bwtween different strides  until try your code.  Maybe this is what makes me stuck  in recent months. Thank you.

**Comment by sketchplanet** [comment]
@yil8 Previously I generate heatmap in level 8(extracting patch without overlap). I didn't realize the huge difference bwtween different strides until try your code. Maybe this is what makes me stuck in recent months. Thank you.
