### ISSUE TITLE
Why is there no NCRF without hard negative mining in the probability map?

### ISSUE THREAD

**Issue by Lotus-95** [baidu-research/NCRF#50]
Thanks for your great work. I want to know the probability map in NCRF without hard negative mining, which I think it's more comparable with the baseline, but it seems like you didn't show this in the paper or README file. So I wonder why is there no NCRF without hard negative mining in the probability map?

**Comment by yil8** [comment]
@Lotus-95 Thanks for your interest in our work. I remember it was because NCRF results without hard negative mining was also bad, but I forgot if it was worse or better than baseline without hard negative mining.
