### ISSUE TITLE
 the coordinates of pre-sampled patches

### ISSUE THREAD

**Issue by 110dazhi** [baidu-research/NCRF#52]
How did you get  the coordinates of pre-sampled patches？tumor_train.txt，tumor_train.txt，tumor_valid.txt，normal_valid.txt

python NCRF/wsi/bin/patch_gen.py /WSI_TRAIN/ NCRF/coords/tumor_train.txt /PATCHES_TUMOR_TRAIN/
python NCRF/wsi/bin/patch_gen.py /WSI_TRAIN/ NCRF/coords/tumor_train.txt /PATCHES_NORMAL_TRAIN/
python NCRF/wsi/bin/patch_gen.py /WSI_TRAIN/ NCRF/coords/tumor_valid.txt /PATCHES_TUMOR_VALID/
python NCRF/wsi/bin/patch_gen.py /WSI_TRAIN/ NCRF/coords/normal_valid.txt /PATCHES_NORMAL_VALID/

**Comment by yil8** [comment]
@110dazhi Hi, can you take a look at this thread of discussion? https://github.com/baidu-research/NCRF/issues/29

**Comment by 110dazhi** [comment]
Sorry I didn't see this. But there is no problem now, thank you. I will try to run the code. And try to see if there are any improvements that can be used to complete my graduation project. Do you have any good suggestions.

**Comment by yil8** [comment]
@110dazhi maybe you can take a look at all the other papers citing this one and see what they have been doing ?
