### ISSUE TITLE
question about "probs * pairwise_potential - (1 - probs) * pairwise_potential"

### ISSUE THREAD

**Issue by 110dazhi** [baidu-research/NCRF#55]
非常感谢能够拜读你的论文和代码，我在看CRF layer时，对这个公式"probs * pairwise_potential - (1 - probs) * pairwise_potential"有一点不理解，（通过 #13 已经知道在代码里有详细介绍，同时在看代码的时候也注意到了）
这个是不是用的这个公式来的，我看是期望，期望的话，是不是
![expectation](https://user-images.githubusercontent.com/57225932/129444223-b691d58a-08f7-46eb-b197-cd8842e97950.png)
probs 是i 为tumor的概率，pairwise_potential 对应的是W的相似性的一个新的值，就像如果向量很相似，那角度就是0，对应的值就是cos 就是1，那他们的w就是一样的，如果角度是180那就是完全相反情况，那值w就是相反的为-1*w，所以在  1. i=T,j=T; 2. i=N,j=T; 3. i=T,j=N; 4. i=N,j=N
 的四种情况的第一种和第四种，就是数据+pairwise_potential出现的概率为probs，所以case1 是‘probs * +pairwise_potential’，同理第四个就是 i 为normal,那其概率就是 1-probs, 事件 是相反的， 所以就是 -pairwise_potential，所以case 4 是 ‘(1 - probs) * -pairwise_potential‘ . 
![pair](https://user-images.githubusercontent.com/57225932/129444724-4d0d9241-17a7-4b88-a5f8-f18263bd2600.png)
事件乘以概率，得到期望，然后23是根据’label compatibility‘消除掉的，这一块还没研究，不过想求证下刚刚上述的理解是不是对的，，，已经研究了一个星期了，今天突然感觉理解了，但是不知道对不对，希望得到解惑

**Comment by 110dazhi** [comment]
还有一个问题就是为什么标签兼容项可以达到 ’约束了像素间传导的条件，只有相同标签（label）条件下，能量才可以相互传导。‘然后消去case 2 和case 3,请问有推荐的参考资料看吗

**Comment by yil8** [comment]
@110dazhi 实在不好意这么长时间没有回复，我最近刚加入一家startup有点忙。。。我不一定完全理解你上面文字的表述，但是感觉上是和我想表达的意思是一致的。至于推导的资料，我是基于Kevin Murphy的Probabilistic Machine Learning: An Introduction里面关于conditional random field以及对应mean field method的章节自己推导出来的。
