### ISSUE TITLE
Is this results achieved the SOTA before 2018?

### ISSUE THREAD

**Issue by Lotus-95** [baidu-research/NCRF#56]
Thanks for your great work! I found that Google's results is 0.87 in 2017, which is higher than your results. Is that two results comparable or they are in different setting? And your results is 0.79 in your paper but 0.80 in the [presentation](https://www.youtube.com/watch?v=t0gh5Nl8xFo), what difference between the two results?

**Comment by 110dazhi** [comment]
Hello, I am also working on this code, if you want, we can communicate.email: chenmz0298@163.com

**Comment by yil8** [comment]
@Lotus-95 Hi and thanks for your interest in our work. Do you mind share the link to Google's 0.87 results back in 2017?

**Comment by Lotus-95** [comment]
> @Lotus-95 Hi and thanks for your interest in our work. Do you mind share the link to Google's 0.87 results back in 2017?

https://arxiv.org/abs/1703.02442 in table 1.

**Comment by yil8** [comment]
@Lotus-95 Thanks for pointing me the paper. In that case, I think Google's results are comparable to mine. I further improved the results a little bit after the paper submission and before the MLconf presentation, and thought it was worth sharing since it was not peer reviewed lol...
