### ISSUE TITLE
What is "list.txt"

### ISSUE THREAD

**Issue by SRL94** [baidu-research/NCRF#57]
Hi,

I am studying the class "GridImageDataset". What is the "list.txt"?

Best regards
Sirui

**Comment by yil8** [comment]
@SRL94 Hi, "list.txt" is generated by [patch_gen.py](https://github.com/baidu-research/NCRF/blob/111c7d19fc6c521d2d1a2c285f5bdf525174e73f/wsi/bin/patch_gen.py) which is explained by https://github.com/baidu-research/NCRF#patch-images

**Comment by SRL94** [comment]
Hey, thank you for the explanation. How do you generate these files? I read all closed issues and it seems you have not provided it.

**Comment by yil8** [comment]
@SRL94 Can you be more specific generating what files?

**Comment by SRL94** [comment]
Such as tumor_train.txt

**Comment by yil8** [comment]
@SRL94 Oh yeah, that part was too complex and old to reproduce from me now... #29
