### ISSUE TITLE
I use matplotlib.pyplot.imshow to plot "Test_026.npy", but something go wrong, can u explain how to transpose "Test_026.npy"?

### ISSUE THREAD

**Issue by cumtlzy** [baidu-research/NCRF#64]

**Comment by cumtlzy** [comment]
I have solved this problem by "np.expand_dims", Thanks for your solid work!

**Comment by ghost** [comment]
Hey, I think I met something wrong like u, can you share your code about transpose&plot the test_026_probs_map.npy?
thx
